### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by vpirogov** [conda-forge/onednn-feedstock#73]
While @densamoilov and @spalicki are listed as maintainers they seem to be lacking correct permissions in the repo.

**Exhibit 1**: [CODEOWNERS](https://github.com/conda-forge/onednn-feedstock/blob/main/.github/CODEOWNERS) warnings
![Image](https://github.com/user-attachments/assets/9d6eef0f-8126-4d7a-9d8f-d0186cad325f)

**Exhibit 2**: @densamoilov approval does not count against codeowners
![Image](https://github.com/user-attachments/assets/f57f0ca6-49f4-419d-88c1-f07b3d644bc7)

**Comment by vpirogov** [comment]
+@xhochy, @conda-forge/core

**Comment by vpirogov** [comment]
@conda-forge-admin, please ping conda-forge/core

**Comment by vpirogov** [comment]
Good point, @isuruf. Let me check.

The one for @densamoilov might have expired though.

**Comment by isuruf** [comment]
You should have gotten invitations now. Can you confirm @densamoilov and @spalicki ?

**Comment by spalicki** [comment]
@isuruf I got mine. After accepting I have merge rights to the repo.
